### ISSUE TITLE
✨ ECDSA canonicalHash

### ISSUE THREAD

**Issue by Vectorized** [Vectorized/solady#1040]
- Usecase: poor-man's VRF.
- If `s` > `n / 2`, replace `s` with `n - s`.
- If in 64-byte format, convert to the 65-byte format. 
- keccak256 of the 65-byte format.
- Provide `canonicalHash` and `canonicalHashCalldata`.
- Change the comment to say that ECDSA signatures are not to be used as unique identifiers directly, but we provide a `canonicalHash` implementation that will convert ECDSA signatures into a canonical byte32 hash.

**Comment by atarpara** [comment]
@Vectorized  I am facing issue checking `s` > `n/2` when signature is 64-bytes `(r, vs)` format. So I will skip this checks for this.

**Comment by Vectorized** [comment]
https://eips.ethereum.org/EIPS/eip-2098
