### ISSUE TITLE
🥢 `SafeTransferLib` Assembly is Not Memory Safe

### ISSUE THREAD

**Issue by nlordell** [Vectorized/solady#1053]
As far as I understand the assembly in `SafeTransferLib` is not memory safe despite being tagged as such. In particular from the [docs](https://docs.soliditylang.org/en/v0.8.26/assembly.html#memory-safety):

> In particular, a memory-safe assembly block may only access the following memory ranges:
> * Memory allocated by yourself using a mechanism like the allocate function described above.
> * Memory allocated by Solidity, e.g. memory within the bounds of a memory array you reference.
> * The scratch space between memory offset 0 and 64 mentioned above.
> * Temporary memory that is located after the value of the free memory pointer at the beginning of the assembly block, i.e. memory that is “allocated” at the free memory pointer without updating the free memory pointer.
>
> Furthermore, if the assembly block assigns to Solidity variables in memory, you need to assure that accesses to the Solidity variables only access these memory ranges.
>
> Since this is mainly about the optimizer, these restrictions still need to be followed, even if the assembly block reverts or terminates. As an example, the following assembly snippet is not memory safe, because the value of `returndatasize()` may exceed the 64 byte scratch space:
>
> ```
> assembly {
>   returndatacopy(0, 0, returndatasize())
>   revert(0, returndatasize())
> }
> ```

In particular, writing over the zero-memory slot (start at memory offset `0x60`) is not allowed in memory safe assembly, even control never leaves the execution block (such as with an explicit `return` or `revert`) or, AFAIU, if the memory is restored. However, in `safeTransferFrom` (among other functions), this invariant is not upheld by the assembly block:

https://github.com/Vectorized/solady/blob/5f048036524032e31c692888f3e8bdf55f6c5209/src/utils/SafeTransferLib.sol#L201

AFAIU, this is an issue as the optimizer may make use of assumptions of the memory layout invariants **within** assembly block statements (one such example, although not applicable to the zero slot, is that stack variables a-la `let x := ...` can occupy memory instead of a stack slot when simultaneous access to more than 16 stack variables is needed).

**Comment by atarpara** [comment]
> assembly {
>  returndatacopy(0, 0, returndatasize())
>  revert(0, returndatasize())
> }

It doesn't cause any issue because return or revert statement will stop current frame execution and returns data to parent frame. 

> https://github.com/Vectorized/solady/blob/5f048036524032e31c692888f3e8bdf55f6c5209/src/utils/SafeTransferLib.sol#L201

We will restore zero-pointer at end of function.

**Comment by nlordell** [comment]
> It doesn't cause any issue because return or revert statement will stop current frame execution and returns data to parent frame.

Correct, but the Solidity documentation **explicitly** states that this is **not** memory safe, despite stopping the current frame of execution. From the docs:

> Since this is mainly about the optimizer, these restrictions still need to be followed, even if the assembly block reverts or terminates.

---

> We will restore zero-pointer at end of function.

Yes, but according to the documentation, this is not enough for the assembly to be considered memory safe. It cannot be written to in the first place.

**Comment by atarpara** [comment]
The Solidity optimizer doesn't change the control flow of functions, so we don't need to worry about this warning.

For a quick example:

```solidity
struct Shit {
    uint256 a;
    uint256 b;
}

function start() public {
    uint256 m;
    assembly {
        m := mload(0x40)
        mstore(0x40, randomBytes)
        mstore(0x60, randomBytes)
    }
    f2();

    assembly {
        mstore(0x40, m)
        mstore(0x60, 0)
    }
}

function f2() public {
    string memory r = "shitmemory";  // load memory pointer and store from there
    Shit memory s;  // assign s to 0x60
    // do stuff
}
```

In the above example, overwriting the free memory pointer and zero pointer like that can cause unexpected errors due to the control flow change from the `f1()` to the `f2()` function, which is written in Solidity. Solady libraries don't give control flow to any other function like the one mentioned above.

**Comment by atarpara** [comment]
Yup it will return `42` because you are writing arbitrary memory pointer location without knowing free memory pointer(0x40). 

Correct ways is writing memory

```solidity
contract MemoryUnsafe {
    function memoryUnsafe() public pure returns (uint256) {
         // all vars
        assembly ("memory-safe") {
           let m := mload(0x40) // where can write memory
            mstore(m, 11) // random memory store...
            mstore(0x00, add(allvar)))
            return(0x00, 0x20)
        }
    }
}
```

**Comment by nlordell** [comment]
> Correct ways is writing memory

Exactly... the current code is writing to `0x60` which is not "the correct way of writing memory" according to the Solidity docs.

**Comment by atarpara** [comment]
> Basically I'm arguing that, while the current code does work, it is relying on UB, and the compiler/optimizer is free to make use of mload(0x60) == 0 assumption at any point inside memory-safe assembly blocks, an invariant which the current assembly block breaks. It can break things silently and unexpectedly in future versions of the compiler.

Solady all assembly block has special comment `/// @solidity memory-safe-assembly` which will disallow this type of future breaking change.

![image](https://github.com/user-attachments/assets/73d115ce-0676-4315-b0b1-1cb62fc1bdec)

**Comment by Vectorized** [comment]
Defacto memory safe.

Closing this.

**Comment by nlordell** [comment]
Ah - OK, so they are relaxing the definition of memory safety to allow overwriting the zero slot as long as it is restored. Looking at the discussion, it means that you can't access dynamic arrays reliably (since you may be inadvertently modifying their length), but that isn't an issue for the safe transfer functions.

TIL - thanks for the link, I wasn't aware of the proposed change.
