### ISSUE TITLE
🐞 SafeTransferLib does not revert for non-existent contracts.

### ISSUE THREAD

**Issue by bull-haus** [Vectorized/solady#1064]
`call`-ing a non-existent contract returns with `1` and a `returndatasize()` of `0`. Since no code was executed, `retOffset` is not overwritten.

For `SafeTransferLib` this leads to the situation where a non-existent ERC20 does not revert on `safeTransfer` and related functions. This behavior is different from e.g. OpenZeppelin's, where it is verified that a contract has indeed been called when `returndatasize()` is `0`. (see https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol#L161).

Unless explicitly documented, a revert should be expected in such cases.

**Comment by Vectorized** [comment]
The NatSpec has already warned that it is the user’s (i.e. dev’s) responsibility to check if the token exists. 

Solady has a different set of priorities from OpenZeppelin.
