### ISSUE TITLE
⚡️ Smol STL safeTransferFrom

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#1135]
Since most ERC20 transferFrom patterns are a "pull" into the calling contract, we can likely provide an optimized variant that omits the `to` argument and hardcode `address()`. Just putting this out there, https://github.com/Vectorized/solady/blob/main/src/utils/SafeTransferLib.sol#L195

**Comment by Vectorized** [comment]
Ah, the amount of gas saved will be miniscule, and it feels weird if we only have a 

```solidity
function safeTransferFromToThis(address token, address from, uint256 amount)
```

cuz there are the `try` variants and the `TransferAll` variants.

**Comment by z0r0z** [comment]
fair nuff. Bigger risk of STL meccha bloat. Closing 🖖
