### ISSUE TITLE
`SignatureCheckerLib.isValidSignatureNow` inaccurate docs

### ISSUE THREAD

**Issue by frangio** [Vectorized/solady#1136]
https://github.com/Vectorized/solady/blob/d87a6baaea980b54f6d0f2d3a3c30c45a5b1520a/src/utils/SignatureCheckerLib.sol#L30-L31

The implementation first attempts `ECRECOVER` and falls back to ERC-1271 if that fails, so it works opposite to what the documentation describes.

**Comment by Vectorized** [comment]
Ok, will update. Nice catch.
