### ISSUE TITLE
✨ STL totalSupply()

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#1211]
here abouts maybe (https://github.com/Vectorized/solady/blob/main/src/utils/SafeTransferLib.sol#L398)

**Comment by atarpara** [comment]
@z0r0z can you elaborate your future more?

**Comment by z0r0z** [comment]
oh, what I mean @atarpara Since Solady has a convenience to cheaply call a token and safely get a balance return, we might do the same for getting the total supply.

**Comment by z0r0z** [comment]
here is a not safe way to do it:
```solidity 
function _totalSupply(address token) internal view returns (uint256 supply) {
        assembly ("memory-safe") {
            mstore(0x00, 0x18160ddd) // `totalSupply()`.
            if iszero(staticcall(gas(), token, 0x1c, 0x04, 0x20, 0x20)) {
                revert(codesize(), codesize())
            }
            supply := mload(0x20)
        }
    }

**Comment by Vectorized** [comment]
We can probably add it. But for this one, we must add a `bool hasTotalSupply` along with the return args.

Cuz `totalSupply` isn't part of the spec.

**Comment by Vectorized** [comment]
```solidity
mstore(0x00, 0x18160ddd) // `totalSupply()`.
hasTotalSupply := and(
    gt(returndatasize(), 0x1f),
    staticcall(gas(), token, 0x1c, 0x04, 0x00, 0x20)
)
result := mul(hasTotalSupply, mload(0x00))
```

**Comment by Vectorized** [comment]
Should probably call it `tryGetTotalSupply`.

**Comment by Vectorized** [comment]
Opps, `totalSupply` is indeed part of the ERC20 spec. Ok, let's add

**Comment by z0r0z** [comment]
init here https://github.com/Vectorized/solady/pull/1212

**Comment by z0r0z** [comment]
peak efficiency thx!
