### ISSUE TITLE
✨ weth helper

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#1222]
honestly can't remember if brought up before, but I think WETH is such a common thing that we might consider a branch or something to that effect that handles WETH stuff. Like deposit, wrap and unwrap through eth send.

**Comment by Vectorized** [comment]
But WETH has a different address on different chains.
Even if we have a create2 onchain registry that returns the WETH address for all chains, it would not be safe and feasible to manage.

**Comment by z0r0z** [comment]
One might, check the chain.sol 🤔 💭  But I appreciate the point and this seems outside scope. Closing for now :~).
