### ISSUE TITLE
Bytes length difference

### ISSUE THREAD

**Issue by woogie96** [Vectorized/solady#1242]
Hi! I am getting a lot of help from your code.

I have a question. Is there a reason why you made the byte length of the slot position value and the slot seed value different?

https://github.com/Vectorized/solady/blob/0dfa99736008ee4d0ee3cd0edd24e2fcfa227b8e/src/tokens/ERC20.sol#L73
https://github.com/Vectorized/solady/blob/0dfa99736008ee4d0ee3cd0edd24e2fcfa227b8e/src/tokens/ERC20.sol#L81

**Comment by Vectorized** [comment]
`_TOTAL_SUPPLY_SLOT` needs to be large enough so that it doesn’t collide with the lower slots.

**Comment by Vectorized** [comment]
Generally, no hard rule on byte lengths. The number of bytes in entropy varies, depending on mood.

**Comment by woogie96** [comment]
Oh, i see. I appreciate to your answer.
