### ISSUE TITLE
✨ DynamicBufferLib

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#141]
[`DynamicBuffer`](https://github.com/samkingco/cozyco/blob/main/contracts/utils/DynamicBuffer.sol) is a snippet that makes concatenating big strings cheaper. For example if you want to construct an SVG out of `<rect>`s this is way better than `abi.encodePacked` or `string.concat` or, dare I say, even better than SOLADY `concat`?

There are different versions of this all over the place. It would be cool to have one true optimized version in this great library!

**Comment by RogerPodacter** [comment]
If I may, speaking on behalf of the entire Solady contributor community, I think this would be cool!

**Comment by Vectorized** [comment]
Sounds **_very_** interesting. 

I'd suggest that it will simply have an `append` function, that will dynamically resize the buffer by 2x if it exceeds the allocated memory.

**Comment by RogerPodacter** [comment]
I agree! I never understood why I have to worry about `allocate`ing the right amount of space. I always just pick a random large-ish number (256kb?) and it has been fine. If I can just `append` without worrying about the allocation that would be great.

Also the version I'm using even calls it `appendSafe`, which, what is the use-case for unsafely append past the capacity of the thing exactly? 

However I must admit I'm not so familiar with assembly and the performance considerations here and, e.g., how this will differ from the way your existing string `concat` works.

**Comment by Vectorized** [comment]
@RogerPodacter https://github.com/Vectorized/solady/pull/146
