### ISSUE TITLE
Feature Request: Add `BokkyPooBahsDateTimeLibrary`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#152]
This is a longish-shot because the lib is moderately niche, but just to stir the pot and get some ideas out there, a snippet I use that's not on NPM and hasn't been updated in a while and is probably unoptimized is [BokkyPooBahsDateTimeLibrary](https://github.com/bokkypoobah/BokkyPooBahsDateTimeLibrary).

Use-case example: [The CryptoPhunk Auction Flywheel](https://www.phunks.pro/) buys NFTs on-demand. The Flywheel uses its ETH balance to buy, but it can't use the entire balance in one week. Instead there is a weekly allowance.

I used BokkyPooBahsDateTimeLibrary to create [a `getStartOfWeek` function that works out this logic](https://etherscan.io/address/0x86b525ab8c5c9b8852f3a1bc79376335bcd2f962#code#F1#L388).

You could imagine this being used in other throttling-type situations, e.g., preventing someone from making 10 DAO proposals in one sitting.

Actually maybe this is a pretty useful library after all...

**Comment by Vectorized** [comment]
Hmm... the library looks small enough. 

May consider.

**Comment by Vectorized** [comment]
@Atarpara You wanna work on this?
