### ISSUE TITLE
Discussion: Should _GAS_STIPEND_NO_GRIEF be 30,000?

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#178]
Iconic NFT collection Azuki [recently used this value](https://etherscan.io/address/0xa8726abb946c55bd1ed29edf63d0f0725b44ae7d#code#F1#L304) in their heavily-memed Skateboard Auction.

The Nouns auction house [does the same](https://etherscan.io/address/0xf15a943787014461d94da08ad4040f79cd7c124e#code#F1#L258).

Given that auctions are a major use-case for safe ETH transfers, does this mean that Solady should take its cues from these major players? Or does it mean that the major players are just intra-player copy-pasting and there's nothing special about 30k.

After all, Azuki didn't use a fallback of any kind, which is certainly something Solady should *not* copy.

Just a thought!

**Comment by Vectorized** [comment]
100000 is in anticipation of the EIP that wants to double the cost of SSTORE. I think this is a good number and will not change it.

**Comment by RogerPodacter** [comment]
True! I agree 100%.

(...Though if non-EOAs cannot bid, why not just use `transfer`?)

Terrifying that it might double like that! Better get all the Punk Derivs out of my system before then!
