### ISSUE TITLE
Proposal: `toHexString` should not prefix with "0x" (or add `toHexStringNoPrefix`)

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#183]
The "0x" prefix is purely stylistic and should be the user's responsibility to add if they want it.

This is consistent with JS behavior: `(255).toString(16) == 'ff'`

Alternatively, if this breaks too many things, it could be good to add a `toHexStringNoPrefix` function like [Uniswap has](https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/HexStrings.sol).

``` solidity
function toHexStringNoPrefix(uint256 value, uint256 length) internal pure returns (string memory) {
    bytes memory buffer = new bytes(2 * length);
    for (uint256 i = buffer.length; i > 0; i--) {
        buffer[i - 1] = ALPHABET[value & 0xf];
        value >>= 4;
    }
    return string(buffer);
}
```

Just a thought!

**Comment by Vectorized** [comment]
Yes. I think the prefix is a PITA. It’s there just to keep API similarity with OZ. 

Will add the no prefix version.
