### ISSUE TITLE
Idea: add LCG to `LibPRNG`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#188]
`shuffle` is great, but if you're trying to pseudo-randomize more than ~10k tokens in `tokenURI` it will exceed 30M gas.

In a project I worked on called [Punk Pixels](https://opensea.io/collection/punkpixels) we wanted to shuffle every non-background pixel in every CryptoPunk (which was about 2M tokens).

To accomplish this I used an LCG of the form:

```solidity
function tokenIdToPixelIndex(uint tokenId) private pure returns (uint) {   
    return ((tokenId + offset) * bigPrimeNumber) % maxSupply;
}
```

It makes sense that LibPRNG shouldn't store big prime numbers, but if it took a BYOP ("Bring Your Own Prime") approach it could offer a shuffling solution for much larger sequences.

Thoughts?

**Comment by Vectorized** [comment]
`testPRNGShuffleGas` which simulated shuffling a 10k array takes `1610904` gas.

**Comment by RogerPodacter** [comment]
TRUE! However that's an array of all zeros. If you populate it with token ids, now you're in the 2.5M range, and then BOOM, you move up to 100k tokens (as in the iconic "Otherdeeds" collection) and you're over 30M gas!

Basically my claim is that Solady currently has no solution for randomizing the order of a 100k collection, and I think Solady should support "the little guy" in creating 100k collections just like Yuga!

At the same time, that many tokens is a tad niche, and my 2M token Punk Pixels nicher still, so I understand if this is beyond the scope of what Solady wants to do right now.
