### ISSUE TITLE
Feature Request: Add `ReentrancyGuard`

### ISSUE THREAD

**Issue by Raiden1411** [Vectorized/solady#192]
This is a long shot but i think it may be worth a try. 

So the idea here is to have solady with all the "standard" contracts much like oz and solmate have. 

This way when working with solady as your library of choice you can have all the tools at your disposal instead of having to import from different libraries (unless its very specific). This would make the project have less "bloat" and be cleaner overall.

The code bellow passes on all of solmate's tests as well as saving 100 gas on protected calls.

```solidity
abstract contract ReentrancyGuard {

    uint256 private constant _UNLOCK = 1;
    uint256 private constant _LOCKED = 2;
    uint256 private constant _REENTRANCY_SELECTOR = 0xab143c06;

    uint256 private _locked = _UNLOCK;
    
    error Reentrancy();

    modifier nonReentrant() virtual {
    
        /// @solidity memory-safe-assembly
        assembly{
            if iszero(eq(sload(_locked.slot), _UNLOCK)) {
                mstore(0x00, _REENTRANCY_SELECTOR)
                revert(0x1c, 0x04)
            }

            sstore(_locked.slot, _LOCKED)
        }

        _;
        
        /// @solidity memory-safe-assembly
        assembly{
            sstore(_locked.slot, _UNLOCK)
        }
    }
}
```

**Comment by Vectorized** [comment]
I'd actually encourage devs DIY their own reentrancy guard (packed with other variables). 

Hmm...

**Comment by Raiden1411** [comment]
I agree with that statement, much like you did with ERC721A. 

However not all devs will do it and this would be a option for them to use in case they need it. 
If you think this goes against the philosophy defined in (#175) feel free to close this issue. But since solady tries to have optimized gas snippets on all areas I though this could belong here.

**Comment by z0r0z** [comment]
I think we might reopen this just to entertain the doubts of contract developers, particularly if an upgrade path (so v0 might have ReentrancyGuard, while v1 bakes). Whether we like it or not, RG is sticky af and often just tells external parties what cannot happen even if wasteful.
