### ISSUE TITLE
Legit Suggestion: add `length()` to `LibString`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#210]
String length is one of the classic "chain shame" topics because it's so complicated how could Solidity ever get it right and you better stick to JS.

On the other hand, there are many instances where you need on-chain string length to validate, most-famously in the case of ENS. They use [this function](https://github.com/ensdomains/ens-contracts/blob/master/contracts/ethregistrar/StringUtils.sol):

```solidity
function strlen(string memory s) internal pure returns (uint256) {
    uint256 len;
    uint256 i = 0;
    uint256 bytelength = bytes(s).length;
    for (len = 0; i < bytelength; len++) {
        bytes1 b = bytes(s)[i];
        if (b < 0x80) {
            i += 1;
        } else if (b < 0xE0) {
            i += 2;
        } else if (b < 0xF0) {
            i += 3;
        } else if (b < 0xF8) {
            i += 4;
        } else if (b < 0xFC) {
            i += 5;
        } else {
            i += 6;
        }
    }
    return len;
}
```

Users should be able to build contracts that validate and register ENS names. In addition, they should be able to build ENS-like services, or services that merely exist in a length-aware world.

It would be cool to duplicate the functionality of this code but in a more efficient way, AND ALSO to have a string length function that does a better job of faithfully computing what a human would call string length than does this code (so the next time someone builds ENS they will do it better).

Thoughts?

**Comment by Vectorized** [comment]
I will call it `runeCount`.

**Comment by Vectorized** [comment]
But even if we have this feature, handling strings rune by rune is crazy bloated. 

Is there a good use case for `runeCount`, just by itself?

**Comment by RogerPodacter** [comment]
Main use-case across the board is user input validation. Probably no one will build ETH twitter, so ENS might be the biggest use-case for a long time.

However, even if it's ONLY FOR ENS, I believe it is worth it, as ENS has been the #1 meme NFT of 2022, it has a TON of staying power, and basically we are living in a golden age of ENS copy-paste. For example:

- https://app.fantomdomains.io/
- https://www.zks.domains/
- Aave also has one though I can't recall the URL. There are a ton more that have cropped up in the past 6 months too, trust me!

Everyone wants their own little ENS clown, and will appreciate the highest-quality tooling.

Another direction if you wanted to get truly based would be to attack the question of on-chain normalization / validation beyond length. This problem has been referred to as the ["Holy Grail" of normalization](https://discuss.ens.domains/t/on-chain-ens-domain-normalization/13202) and could prevent trolls like me from registering things like [BOOOOM.eth](https://etherscan.io/tx/0xba309aee91eb48a606d2bb1abb18e23f8fabfc549700c71b1f7b0c9db4584e4b) and [0..99.eth](https://etherscan.io/tx/0x0162b066376308591038c0b568295d7e121af7db602c63e6485311b0dc826735)

(Though more likely it would be too expensive to do within a transaction but still would be super-helpful for people building ENS registration enabled dapps who didn't want to get too into the surrounding JS ecosystem.)
