### ISSUE TITLE
Could be good? Add `appendBase64()`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#237]
[Ethier's DynamicBuffer](https://github.com/divergencetech/ethier/blob/main/contracts/utils/DynamicBuffer.sol) has a function called `appendSafeBase64()` that appends and base64-izes data simultaneously. I don't know assembly but this seems potentially more efficient than one at a time!

Interestingly Solady is given an author credit on the function.

**Comment by RogerPodacter** [comment]
Wow no love for this one? Am I finally falling off?

Use case here is this.

Old way:

1. Generate big SVG or BMP image
2. Base64 it
3. Append it to a JSON string using a DynamicBuffer

End result being a JSON string with the image in B64 format at the end.

"Proposed new way"

1. Generate big SVG or BMP image
2. Base64 it while simultaneously appending the B64 data to the buffer!

End result is the same!

In my informal testing it was up to a 10% gas savings for large BMPs.

Mainnet Etherscan has a ~100M read gas limit so if you want the "cred" of an "on-chain" NFT that shows a ton of data for tokenURI there, you need to think about gas!

Thoughts?

**Comment by Vectorized** [comment]
I think keep as separate functions for now. 

If someone is actually hitting the gas limit, try using `LibString.directReturn` first.
