### ISSUE TITLE
✨ LibSort difference, union, intersection

### ISSUE THREAD

**Issue by Vectorized** [Vectorized/solady#240]
Kinda like set operations, but inputs and outputs are all sorted.

Does not need to check that inputs are sorted.

All operations must be O(n).

Anyone game, comment below. 

Include variants for for uint, address, int.

Testing on address and int variants optional. 

The tests would be interesting. Try make the tests as compact but as complete as possible. 🤔

**Comment by Vectorized** [comment]
![770B4E82-F376-4671-8377-DA1326B71429](https://user-images.githubusercontent.com/5889274/208356720-f82b1a10-bc6a-4bbc-bf1f-693f28955ded.png)

Holy shit. Thank you ChatGPT.

Anyway, just write it in assembly as much as possible.

**Comment by Vectorized** [comment]
Try the follow ChatGPT commands:

Write me a Solidity method to return the union of two sorted arrays.

Write me a Solidity method to return the difference between two sorted arrays.

Write me a Solidity method to return the intersection between two sorted arrays.

**Comment by Atarpara** [comment]
@Vectorized I am on it.
