### ISSUE TITLE
Feature Request: Add strict ERC1271 Signature Checking to `SignatureCheckerLib` 

### ISSUE THREAD

**Issue by YamenMerhi** [Vectorized/solady#264]
### Motivation

In the current `SignatureCheckerLib`, there is support to check if a signature is valid with the `isValidSignatureNow(..)` function that checks the following:
- If the `hash` and `signature` recover an address that is the same as the `signer`, it returns true.
- When it's not the case, it calls `isValidSignature(..)` on the `signer` assuming it's a contract. 

What would be a great addition to the library is to have another internal function that checks if a signature is valid with **ERC1271** only. So calling `isValidSignature(..)` directly on the signer implementing ERC1271.

This function will be useful for functions that want to interact only with wallets such as argent, gnosis, etc .. and check the signature **only via ERC1271**. 

Then this internal function can be re-used in `isValidSignatureNow(..)`.

### Details

Developers can interact with other smart contract wallets via calling `isValidSignature(..)` function directly. Still, they need to handle the return value, so the new function can be a wrapper named `isValidERC1271SignatureNow(address,bytes32,bytes)` that calls `isValidSignature(..)` on the address with the hash and the signature with `staticcall` and don't revert if the function doesn't exist and return true or false, depending if the function returns the `isValidSignature.selector`. Exactly like what the code do in the second part of the `isValidSignatureNow(..)` function.

The code in solidity would be something like this:
```solidity
function isValidERC1271SignatureNow(address signer, bytes32 dataHash, bytes memory signature) internal view returns (bool) {
  
        (bool success, bytes memory result) = signer.staticcall(
            abi.encodeWithSelector(IERC1271.isValidSignature.selector, hash, signature)
        );
        return (success &&
            result.length == 32 &&
            abi.decode(result, (bytes32)) == bytes32(IERC1271.isValidSignature.selector));
}
```

If you find this addition relevant, I can work on creating the new one in yul (splitting the isValidSignatureNow function into a new one).

**Comment by Vectorized** [comment]
@YamenMerhi See if #265 is what you want.

**Comment by YamenMerhi** [comment]
@Vectorized So quick! Yes, this is it thanks!
