### ISSUE TITLE
Add support for git tags to be used in `forge install`

### ISSUE THREAD

**Issue by StErMi** [Vectorized/solady#284]
I was looking at Damn Vulnerable DeFi v3 and that CTFs uses `Solady v0.0.67`.

I'm using foundry as my test suite, so I tried to install the dependency via `forge install Vectorized/solady@v0.0.67` but this specific command is looking for a tag and as far as I can see Solady do not push tag/releases.

Foundry support different installation ways with [`forge install` ](https://book.getfoundry.sh/reference/forge/forge-install)

- branch
- tag
- commit

And I could install that specific `v0.0.67` by looking at the commit history, but I think that it would be much better for projects if they could pin to a specific version by using the tag.

**Comment by Vectorized** [comment]
Done, thanks.
