### ISSUE TITLE
❔ ERC165 support in Ownable/OwnableRoles

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#295]
Arguments for: *EIP says "should"* 
Arguments against: _OZ and Solmate don't implement._

![image](https://user-images.githubusercontent.com/92001561/215708167-7138f2cf-0152-48e3-bf34-a3b1abe59376.png)

At very least, I am curious if we can describe an optimized yul version of `supportsInterface` that can be weaved into contemporary use of ERC165, like NFTs.

This issue is opened up for discussion. I personally find ERC165 a bit crufty.

**Comment by Vectorized** [comment]
Might make it more inconvenient because of the need to carefully override stuff. Most platforms (e.g. OpenSea) are already capable of handling Ownables without ERC165.
