### ISSUE TITLE
"Bold" Idea? `multicall` shouldn't be `payable`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#298]
Multicall is not safe with `msg.value`. Yet there are very few (if any?) use-cases for a function to accept eth and yet not rely on `msg.value` in any way.

Removing `payable` would invalidate this tiny set of use-cases, but on the positive side it would prevent me from losing 300M USD in the majority of cases (as your linked blogpost describes). I guess removing it would also cost more gas (as you famously argued in the case of ERC721A functions).

[OZ's version](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Multicall.sol) is not payable, and the version you link (`https://github.com/transmissions11/solmate/blob/main/src/utils/Multicallable.sol`) seems to no longer exist!

If you don't want to break backwards incompatibility (which I think is warranted), perhaps adding `SafeMulticallableUseThisOnePlease.sol` could work.

Thoughts?

Ps. What would a "a suitable nonce mechanism" even be here? I guess a function could look at `msg.sig` to determine whether it's in a multicall and therefore cannot trust `msg.value`? Or maybe the multicall function itself could set a `isInMultiCall` state variable like reentrancy?

None of these seem good to me!

**Comment by Vectorized** [comment]
Payable gud.

**Comment by RogerPodacter** [comment]
Haha okay in that case: "use-case challenge bounty": I challenge you to name a single real-world use-case that would be messed up by the removal of payable! (You always ask me about use cases...)

BTW while I'm in "anti-payable aggro mode," was it even a good idea to add the payables to ERC721A? Saves a tiny amount of gas, but now I can't prevent people from sending dust to my contract which can make auditing the flow of eth in and out of the contract more difficult...

(Am I being too aggro?)

**Comment by 0xdapper** [comment]
If you dont make it payable you wont be able to call payable functions in the multicall

**Comment by RogerPodacter** [comment]
Correct, and I don't think calling payable functions in a multicall is a valid use-case as these payable functions inevitably rely on `msg.value` in some way and `msg.value` cannot be trusted in the multicall context.

Even if you had a use-case for a payable function that doesn't rely on `msg.value`, that's not enough. You must also ensure that none of your *other* payable functions rely on `msg.value`.

Not a lot of use-cases and a huge vulnerability if you use it incorrectly.

Thoughts?

**Comment by 0xdapper** [comment]
Yes, fair points, but any dev encoding a multicall is competent enough to know these risks imo. Not opposed to a safe option without a multicall, but opposed to removing it in entirety.

**Comment by 0xdapper** [comment]
I think could just make Multicall a library and let anyone wanting to expose it decide how they want to do it, external, authed, payable, not payable, all variations possible with a library.

**Comment by RogerPodacter** [comment]
I agree with that approach, I just think that it should be safe (non-payable) by default, even if this burdens the 0.00001% of devs who have a valid payable use-case.

Even now, as I rack my brain, I can't think of a single valid use-case for a payable multicall!

One model for naming / self-documenting it might be React's `dangerouslySetInnerHTML`, e.g. `unsafePayableMulticall`.

**Comment by z0r0z** [comment]
So, I just made a version without payable that I call `SafeMulticallable` lol, not sure if helpful, https://github.com/Sol-DAO/solbase/blob/main/src/utils/SafeMulticallable.sol

**Comment by Vectorized** [comment]
@z0r0z maybe i should also make it non-payable here.

**Comment by Vectorized** [comment]
Thanks all for the discussion. 

Looks like 20+ more gas is worth the extra flexibility.

**Comment by RogerPodacter** [comment]
Yes!! Thank you!! I promise, it's definitely worth 20 extra gas to prevent me from accidentally blowing my brains out!
