### ISSUE TITLE
Docs addition: are Solady libraries upgrade-safe?

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#299]
Might be good to mention this in the docs.

Though I guess they aren't because they don't have the `uint256[46] private __gap` meme?

**Comment by Vectorized** [comment]
Yes. All of the contracts use custom storage layout. It’s kinda like diamond storage, but not exactly.

**Comment by RogerPodacter** [comment]
BOOOOMMMM: https://github.com/Vectorized/solady/pull/300
