### ISSUE TITLE
Free floating library functions - SafeTransfer

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#329]
When I import Solady libraries I should be able to specify the actual functions I want, like {safeTransferFrom} from {SafeTransferLib}, thoughts?

**Comment by Vectorized** [comment]
I prefer non-free-floating functions.

**Comment by z0r0z** [comment]
Fair enough. Maybe it's just me. Will close in a lil while in case anyone else is into this kinda stuff.
