### ISSUE TITLE
✨ Support for arbitrary `uint` types within `utils/Clone.sol`

### ISSUE THREAD

**Issue by 0xClandestine** [Vectorized/solady#382]
**Proposal:** Add something like the `_getPartialWord()` method  below to address limited support for arbitrary `uint`-based types. Alternatively, we could explicitly support each of these types with a method for each. (IE `_getArgUintXXX`)

**Problem:**
Currently, only `uint8`, `uint64`, and `uint256` are fully supported in Solidity. However, there are scenarios where we need to work with other arbitrary uint types, which requires writing custom helper methods to handle them. This can be cumbersome and error-prone.

**Solution:**
We propose adding a `_getPartialWord()` method to the Clone contract to provide a generic solution for working with arbitrary `uint` types. The method uses inline assembly to extract a portion of a `uint256` value based on a specified bit offset and size.

**Example:**
```solidity
abstract contract Clone {
    function _getPartialWord(uint256 argOffset, uint256 sizeBits)
        internal
        pure
        returns (bytes32 arg)
    {
        assembly {
            let offset :=
                sub(calldatasize(), shr(0xf0, calldataload(sub(calldatasize(), 2))))

            arg :=
                shr(sub(0x100, sizeBits), calldataload(add(offset, argOffset)))
        }
    }

    // ...

    function _getArgAddress(uint256 argOffset)
        internal
        pure
        returns (address arg)
    {
        return address(uint160(_getPartialWord(argOffset, 160)));
    }
    
    function _getArgUint96(uint256 argOffset)
        internal
        pure
        returns (uint96 arg)
    {
        return uint96(uint256(_getPartialWord(argOffset, 96)));
    }
}```

**Comment by Vectorized** [comment]
Ok, making a PR for this.

**Comment by 0xClandestine** [comment]
Sick, glad to contribute. 🙏
