### ISSUE TITLE
✨ Run-length encoding

### ISSUE THREAD

**Issue by 0xClandestine** [Vectorized/solady#396]
Would love to see more support for data compression, figured I'd draft a RLE lib for [reference](https://en.wikipedia.org/wiki/Run-length_encoding) to get the ball rolling.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

library RLE {
    function encode(bytes memory data)
        internal
        pure
        returns (bytes memory result)
    {
        unchecked {
            uint256 i = 0;
            uint256 j = 0;
            uint256 encodedLength = 0;

            while (i < data.length) {
                uint256 count = 1;
                while (
                    i + count < data.length && data[i + count] == data[i]
                        && count < 255
                ) {
                    count++;
                }

                encodedLength += 2;
                i += count;
            }

            result = new bytes(encodedLength);
            i = 0;
            j = 0;

            while (i < data.length) {
                uint256 count = 1;
                while (
                    i + count < data.length && data[i + count] == data[i]
                        && count < 255
                ) {
                    count++;
                }

                result[j] = bytes1(uint8(count));
                result[j + 1] = data[i];
                i += count;
                j += 2;
            }
        }
    }

    function decode(bytes memory data)
        internal
        pure
        returns (bytes memory result)
    {
        unchecked {
            uint256 i = 0;
            uint256 j = 0;
            uint256 decodedLength = 0;

            while (i < data.length) {
                uint256 count = uint8(data[i]);
                decodedLength += count;
                i += 2;
            }

            result = new bytes(decodedLength);
            i = 0;
            j = 0;

            while (i < data.length) {
                uint256 count = uint8(data[i]);
                bytes1 value = data[i + 1];

                for (uint256 k = 0; k < count; k++) {
                    result[j] = value;
                    j++;
                }

                i += 2;
            }
        }
    }
}
```

Glad to rewrite this in assembly 🙂

**Comment by Atarpara** [comment]
@0xClandestine have you any good use-case for this?

**Comment by 0xClandestine** [comment]
> @0xClandestine have you any good use-case for this?

Certainly, RLE (Run-Length Encoding) is a valuable technique for lossless data compression. I'm currently utilizing it to condense bytecode used for rendering pixel art on-chain. While this use case may seem specialized, I think anything that could reduce storage costs on the EVM is worth exploring. Glad to discuss this further 🙏

**Comment by RogerPodacter** [comment]
I agree this is a good idea, but IMO consider Deflate over RLE as it is more efficient and versatile.

https://github.com/cxkoda/inflate-sol/tree/master

Here's an INFLATE implementation but I can't find a deflate one! Probably because people aren't really compressing INSIDE the contracts.

**Comment by 0xClandestine** [comment]
> I agree this is a good idea, but IMO consider Deflate over RLE as it is more efficient and versatile.
> 
> 
> 
> https://github.com/cxkoda/inflate-sol/tree/master
> 
> 
> 
> Here's an INFLATE implementation but I can't find a deflate one! Probably because people aren't really compressing INSIDE the contracts.

Funny you mention INFLATE, that was the next thing I wanted to recommend. In regard to choosing one over the other, they actually great when used together. Here's a good article for reference: https://mirror.xyz/0x10072dfc23771101dC042fD0014f263316a6E400/8g7zt8354ZWlOJ5FYvtQ2LP9t0BgOaNKCw4_AEpuQEs

**Comment by Atarpara** [comment]
@RogerPodacter @0xClandestine Awesome Idea. I will start work on this.

**Comment by 0xClandestine** [comment]
> @RogerPodacter @0xClandestine Awesome Idea. I will start work on this.

Awesome, I would be glad to contribute on this as well.

**Comment by RogerPodacter** [comment]
Interesting! My understanding (which admittedly comes mostly from GPT-4) is that DEFLATE already has some RLE-esque things in it such that you generally don't gain much by pre-RLE-ing. I wonder what the results would have been had Nouns has skipped RLE and just DEFLATEd!

In any case, given how much simpler RLE is it's probably nice to have both options.

**Comment by Atarpara** [comment]
@0xClandestine @RogerPodacter As per my understanding of DEFLATE encoding and decoding is complex stuff. Writing this in solidity assembly is trivial task because I didn't fully understand  DEFLATE algorithm working.

**Comment by 0xClandestine** [comment]
> Interesting! My understanding (which admittedly comes mostly from GPT-4) is that DEFLATE already has some RLE-esque things in it such that you generally don't gain much by pre-RLE-ing. I wonder what the results would have been had Nouns has skipped RLE and just DEFLATEd!
> 
> In any case, given how much simpler RLE is it's probably nice to have both options.

Would love to see this comparison on this as well, curious what the results would show.

**Comment by 0xClandestine** [comment]
> @0xClandestine @RogerPodacter As per my understanding of DEFLATE encoding and decoding is complex stuff. Writing this in solidity assembly is trivial task because I didn't fully understand DEFLATE algorithm working.

Perhaps we pivot to [huffman coding](https://en.wikipedia.org/wiki/Huffman_coding), I think we could possibly implement it using `RedBlackTreeLib`.

**Comment by Atarpara** [comment]
@0xClandestine I don't think huffman coding implement using `RedBlackTree` is good idea. To best way implement this is `minHeap`.

**Comment by 0xClandestine** [comment]
> @0xClandestine I don't think huffman coding implement using `RedBlackTree` is good idea. To best way implement this is `minHeap`.

Interesting, would love to discuss this more 🙂

**Comment by Atarpara** [comment]
@0xClandestine In huffman coding problem occurs on frequency counting of every `char` because solidity haven't any data structure like `map`.  There is possible one solution in my mind is custom memory mapping for every character and store there frequency of this char. 

For Example :

Free memory pointer is `0x80`
then we mapped memory 

`0x80-0x9F` location for ASCII char `0x20`  (space)
`0xA0-0xBF` location for ASCII char `0x21` (!)
.
.
0xBC0-0xBCF location for ASCII char `0x7E` (~)

Here some problems :
1. free-memory pointer is unknown it only known when we running this function so memory mapping must be dynamic
2. after calculating frequency we iterate every memory slot ( total 94 slot)


@0xClandestine  @Vectorized  please share your thought on this?

**Comment by Atarpara** [comment]
solady `RedBlackTree Lib` and `Min Heap Lib` is using storage pointer so it quite gas expensive implement with this.
