### ISSUE TITLE
🐞 SSTORE2 can store a max of 24_575 bytes, not 24_576 bytes as expected

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#400]
Expected: I can store max contract size of 24_576 bytes
Actual: I can store 24_576 - 1 bytes

Reproduced in [this contract](https://goerli.etherscan.io/address/0xe5805ff20a7964e09308f4182f4305da7bc8948a):

1. [24_576 bytes failure](https://goerli.etherscan.io/tx/0x23df0f5d63045024f2e488c04c5a931e036a71e084de948743b9462b777d87ab)
2. [24_576 - 1 bytes success](https://goerli.etherscan.io/tx/0xf66922dc9d4472737f0f9c3fd78995dda4e1dd8c928f0c1fd4f3df5f644fe4f0)

Obviously the extra byte doesn't matter practically, but people might rely on being able to store the full 24_576 because it is a meme.

**Comment by Atarpara** [comment]
@RogerPodacter Solady use extra 1 bytes starting of data as a `stop` opcode preventing any call.  so with solady `sstore2` lib only can able deploy 24_575 bytes data contract. For more details you check out here : https://github.com/Vectorized/solady/blob/main/src/utils/SSTORE2.sol#L41
