### ISSUE TITLE
🚨 foundry.toml

### ISSUE THREAD

**Issue by Vectorized** [Vectorized/solady#430]
**Update:**

foundryup should fix it now.

If things break again, comment below.

-------------------

If you have problems compiling your project, it can be due to the latest foundry version erroring if the `foundry.toml` does not contain `evm_version = "shanghai"` when `solc_version = "0.8.20"` is used.

Fix:
- Edit `lib/solady/foundry.toml` to change `solc_version = "0.8.19"`, and remove `evm_version="shanghai"`.
- Force remove solady. `forge remove -f lib/solady`.
- `foundryup` to the latest Foundry version.
- Reinstall solady at the latest version 0.0.96.

If it still does not work, comment below.

**Comment by kyhyco** [comment]
Hello! Found an issue with `evm_version = "paris"` and using anvil + cast.

Steps to reproduce:
```sh
anvil

// on a separate terminal pane
forge init hello_foundry

cd hello_foundry

forge install vectorized/solady

cast chain-id
```

I expect to see `31337` but instead get:
```
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: Unknown evm version: paris for setting `evm_version`

Location: config/src/lib.rs:448
```

Unclear to me if this is an issue with `cast` or `solady`. Would appreciate any insight! Thank you!

**Comment by kyhyco** [comment]
Using
```
forge 0.2.0 (9f6bb3b 2024-03-10T00:17:56.235891000Z)
cast 0.2.0 (ed9298d 2023-03-09T05:36:14.53538Z)
anvil 0.2.0 (9f6bb3b 2024-03-10T00:17:56.195647000Z)
```

**Comment by kyhyco** [comment]
The issue was that `cast` and `forge` were on different versions!
