### ISSUE TITLE
✨ Release memory modifier

### ISSUE THREAD

**Issue by Vectorized** [Vectorized/solady#437]
I wonder where should we put this.

```solidity
modifier releaseMemory {
    uint256 m;
    /// @solidity memory-safe-assembly
    assembly {
        m := mload(0x40)
    }
    _;
    /// @solidity memory-safe-assembly
    assembly {
        mstore(0x40, m)
    }
}
```

**Comment by Atarpara** [comment]
I think we put this where we use `0x40` memory for calculation purpose. Is that gas optimized?

**Comment by Vectorized** [comment]
This is useful for those functions where you do a lot of abi.encode to compute a hash.

**Comment by Atarpara** [comment]
I check this with `ECDSA` lib. Unfortunately it will increase gas cost and codesize. 
Result: `forge s --diff`

![image](https://github.com/Vectorized/solady/assets/66815072/91f53d83-527f-4bdd-971a-6fa1ba88c39b)

**Comment by Vectorized** [comment]
It’s not for everything. Only very specific functions.

**Comment by Atarpara** [comment]
> It’s not for everything. Only very specific functions. 

Yup. But it will increase slightly gas cost and codesize.

**Comment by Vectorized** [comment]
I'll make an example to demonstrate when I have more energy, motivation, and time.

**Comment by Vectorized** [comment]
I think this operator may be accidentally abused to cause issues. Even amongst experts.
