### ISSUE TITLE
Compiler Error: Stack too deep when running solidity coverage

### ISSUE THREAD

**Issue by filipkny** [Vectorized/solady#454]
I'm building a project using the solady ERC1155 implementation. When trying to run my tests with coverage I ran into the error below:

```
Compiler run failed:
Error: Compiler error (/solidity/libsolidity/codegen/ContractCompiler.cpp:847):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
   --> lib/solady/src/tokens/ERC1155.sol:374:9:
    |
374 |         assembly {
    |         ^ (Relevant source part starts here and spans across multiple lines).
```
I have tried compiling and running coverage with '--via-ir' and '--optimize', to no success.

According to the hardhat official docs (https://github.com/sc-forks/solidity-coverage/blob/master/HARDHAT_README.md), contracts are compiled without optimization when running coverage. I'm using Foundry and couldn't find any info specifically for it, but I suspect the same applies, which would explain this error.

This is a bit of a bummer since i'm unable to run coverage on my project as long as I'm using solady's ERC1155 implementation.

Is there any obvious solutions that I'm overlooking, or do I simply need to wait for a patch that optimizes this particular implementaion?

**Comment by Vectorized** [comment]
@filipkny Try the latest version `0.0.100`.

**Comment by filipkny** [comment]
Works perfectly, thanks :)
