### ISSUE TITLE
💡 Upgrade-safe ERC2981

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#462]
That's it. That's the tweet!!!!

**Comment by Vectorized** [comment]
It is upgrade safe, if `name()` and `symbol()` return from storage instead of immutables.

**Comment by RogerPodacter** [comment]
This is the royalties one. Since posting this I've realized it's actually pretty simple to roll your own here if you don't care about per-token royalties which I feel like most people don't. But if you DO want the more complete solution there is no library that does this. `solidstate-solidity` has something but I cannot get it to work for some reason!
