### ISSUE TITLE
✨ Challenge with auto-approving an operator in a gas-efficient manner

### ISSUE THREAD

**Issue by ryanio** [Vectorized/solady#489]
We would like to auto-approve the OpenSea conduit for new SeaDrop tokens, however the ERC721 and ERC1155 implementations access the approval storage slot directly instead of using the isApprovedForAll() fn.

We'd like to do this:

```solidity
   function isApprovedForAll(
        address owner,
        address operator
    ) public view virtual override returns (bool) {
        if (operator == _CONDUIT) {
            return true;
        }
        return ERC1155.isApprovedForAll(owner, operator);
    }
```

but we have to resort to doing this:

```solidity
    function _afterTokenTransfer(
        address /* from */,
        address to,
        uint256[] memory /* ids */,
        uint256[] memory /* amounts */,
        bytes memory /* data */
    ) internal virtual override {
        // Auto-approve the conduit.
        if (to != address(0) && !isApprovedForAll(to, _CONDUIT)) {
            _setApprovalForAll(to, _CONDUIT, true);
        }
    }
```

Would it be possible for the underlying token contracts to use isApprovedForAll() so it can be overridden with custom logic? Also open to other ideas.

Thank you for a great repository!

**Comment by Vectorized** [comment]
Argh, I can't think of a zero-cost abstraction way to do this. I think the best is to copypasta.

**Comment by Vectorized** [comment]
A less efficient way is to override all the external transfer methods to use the internal transfer methods, passing in `by = address(0)` if `msg.sender == _CONDUIT`.

**Comment by ryanio** [comment]
ooh interesting solutions. really appreciate you thinking about this @Vectorized. would love to stay on the canonical repo but can also use a forked version, just would like to get updates over time but shouldn't be too much hassle to keep the fork up to date.

**Comment by ryanio** [comment]
thanks for always listening and helping @Vectorized! if you are curious we just decided to modify the assembly code directly in [Shipyard](https://github.com/ProjectOpenSea/shipyard-core/blob/main/src/tokens/erc721/ERC721ConduitPreapproved_Solady.sol), so i will close this issue for now since it is probably not needed for most others
