### ISSUE TITLE
:lady_beetle: No constructor on ERC721 and ERC20. Is this the intended behavior?

### ISSUE THREAD

**Issue by rookmate** [Vectorized/solady#494]
Hey @Vectorized,

I was going to give Solady's ERC721 a run but noticed that it breaks compatibility with [solmate ERC721](https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC721.sol#L57) as well as [OpenZeppelin's ERC721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L43).

I also checked and ERC20 also breaks compatibility with solmate and OZ.

Is this the intended behavior?

**Comment by Vectorized** [comment]
Yes. It's intended. This is to make it compatible with upgradeable (i.e. proxied) contracts.

**Comment by rookmate** [comment]
Ah got it
