### ISSUE TITLE
🥢 ERC721: what does the double xor achieve in _setExtraData

### ISSUE THREAD

**Issue by 77abe77** [Vectorized/solady#502]
Hey, so ive been gawking over 

```
    /// @dev Sets the extra data for token `id` to `value`.
    /// Minting, transferring, burning a token will not change the extra data.
    /// The extra data can be set on a non existent token.
    function _setExtraData(uint256 id, uint96 value) internal virtual {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x00, id)
            mstore(0x1c, _ERC721_MASTER_SLOT_SEED)
            let ownershipSlot := add(id, add(id, keccak256(0x00, 0x20)))
            let packed := sload(ownershipSlot)
            sstore(ownershipSlot, xor(packed, shl(160, xor(value, shr(160, packed)))))
        }
    }

```
The double xor does seem to ensure that value gets the correct value after the first xor:
`xor(value, shr(160, packed)))`

But Im just wondering, is there anything wrong/bad with just:
` sstore(ownershipSlot, or(packed, shl(160, value)))`

I would appreciate your insight on this, thank you :)

**Comment by 77abe77** [comment]
Also forgive me if gh issues is not the best medium for this question. lmk if these types of q's are better suited for twitter or some other medium :)

**Comment by Vectorized** [comment]
The aim is to replace some of the old bits with the new bits.

One way is to mask out the old bits with an `and`, and do a `or` to overlay in the old bits.

Another way is to do a `xor` with some number that will flip the bits in a way that gives the same result.  
This special number will be the `xor` difference between the old number and the desired final result.  
Hence the double `xor`s.

The second way is sometimes slightly more efficient, and gives more compact bytecode.
