### ISSUE TITLE
✨ add `toUint256(int256)` to `SafeCastLib`

### ISSUE THREAD

**Issue by 0xClandestine** [Vectorized/solady#511]
Noticed both are missing:

Thinking we would check that each param is greater than zero:
```solidity
function toUint256(int256 x) internal pure returns (uint256) {
    if (x < 0) revert FailedConversion();
    return uint256(x);
}
```

**Comment by 0xClandestine** [comment]
Wouldn't hurt to add `complementWad` as well:
```solidity
function complementWad(uint256 x) internal pure returns (uint256 result) {
    assembly {
        result := mul(lt(x, WAD), sub(WAD, x))
    }
}
````

**Comment by 0xClandestine** [comment]
`powWad(uint256, uint256)` could also be added to `FixedPointMathLib`

**Comment by Vectorized** [comment]
@0xClandestine Do you have example use case for `complementWad` and `powWad`? Would prefer if there's a repo out there that already has thought of all the edge cases.

**Comment by Vectorized** [comment]
I think let's leave it as `powWad(int256 x, int256 y)`.

**Comment by 0xClandestine** [comment]
@Vectorized All of this is inspired by Balancer v2 arithmetic:

Complement reference:
https://github.com/balancer/balancer-v2-monorepo/blob/bc3b3fee6e13e01d2efe610ed8118fdb74dfc1f2/pkg/solidity-utils/contracts/math/FixedPoint.sol#L156

Furthermore, for `powWad` we only need to ensure that the signed integers (params) are greater than zero. Although my main issue is with the return value, which requires me to check that `result > 0`. So tbh its not a huge issue.

**Comment by 0xClandestine** [comment]
> I think let's leave it as `powWad(int256 x, int256 y)`.

`powWad(int256, int256) -> (uint256)` could be a happy median

**Comment by Vectorized** [comment]
I think I'll let the people who need `pow` and `wadComplement` copy paste from balancer.

Licensing issue, and risk of edge case unaccounted for.
