### ISSUE TITLE
📝 Bad Solmate Reference Link

### ISSUE THREAD

**Issue by JackBDart** [Vectorized/solady#52]
The [ECDSA file](https://github.com/Vectorized/solady/blob/dadec755923b5aa2b9369a8a492407cd0772c56e/src/utils/ECDSA.sol) has a broken link to a solmate implementation, found in line 6.

The link in question: `https://github.com/transmissions11/solmate/blob/main/src/utils/ECDSA.sol`.

After some digging in the solmate repo, I could not find an implementation of ECDSA, in either the main or v7 branch.

**Comment by Vectorized** [comment]
It’s not there yet. 😉 Just leaving the link there hehe.
