### ISSUE TITLE
✨ Add forceApprove to SafeTransferLib 

### ISSUE THREAD

**Issue by zerosnacks** [Vectorized/solady#525]
In [OpenZeppelin's v4.9 release](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#SafeERC20-safeApprove-contract-IERC20-address-uint256-) `safeApprove` was deprecated in favor of `forceApprove` to deal with an issue in the behaviour of some tokens (specifically USDT) that expect the approval to be set to zero before setting it to a non-zero value.

Before the method existed in OpenZeppelin developers have been using a similar try / catch, see [Euler](https://github.com/euler-xyz/euler-contracts/blob/dfaa7788b17ac7c2a826a3ed242d7181998a778f/contracts/swapHandlers/SwapHandlerBase.sol#L11-L28).

I think it would be great to upstream this behavior into `SafeTransferLib` so users of Solady don't have to implement it themselves.

Optionally we could deprecate `safeApprove` but I think there is a case to be made for both to exist side-by-side in case developers do not need the additional check.

**Comment by Vectorized** [comment]
I'll use the `safeApproveWithRetry`, as `forceApprove` makes `forceSafeTransferETH` inconsistent. 

Also, there may be a non-zero chance that the retry may fail.

**Comment by zerosnacks** [comment]
Awesome, I like your suggested name much more as well!
