### ISSUE TITLE
✨ Add MetadataReaderLib library

### ISSUE THREAD

**Issue by zerosnacks** [Vectorized/solady#529]
In the last few years there has been an increase in protocols that allow for permissionless listing of ERC20's. One of the problems one encounters when designing a protocol like that is how to gracefully handle non-compliant ERC20's with odd `metadata` (name, symbol, decimals) behaviour like MKR that instead of a `string memory` returns a `bytes32`.

In order to do so projects have centered around a set of similar solutions:

- https://github.com/ajna-finance/ajna-core/blob/main/src/libraries/helpers/SafeTokenNamer.sol (which is based on Uniswap's V1's https://github.com/Uniswap/solidity-lib/blob/master/contracts/libraries/SafeERC20Namer.sol)
- https://github.com/sablier-labs/v2-core/blob/fcbc567aea6362c1f102eb19732badeb4899dec5/src/SablierV2NFTDescriptor.sol#L300-L331
- https://github.com/silo-finance/silo-core-v1/blob/master/contracts/lib/TokenHelper.sol

It is also quite common for ERC4626's to derive their name from the underlying ERC20 which has to be handled in the same way as well if creation is permissionless: https://github.com/Rari-Capital/vaults/blob/c8fdddc2a699f8c577e70878998a3eaa7d519f3f/src/Vault.sol#L43-L53

It has previously been requested by @paulrberg in OpenZeppelin (https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4277) but hasn't been picked up yet.

I'm curious to hear what you think. It is not a performance related addition to the library so it is more for convenience and fits in line with the idea that implementation details should be delegated to libraries, not the app (business logic).

It appears that people prefer to have some control over the fallback solution so this is something we preferably would have to take into account though I think there is room for an opinionated solution. Personally I quite like Uniswap / Ajna's method of using the token address.

**Comment by Vectorized** [comment]
Excellent suggestion! 

I feel that it can be named `MetadataReaderLib.sol`. 

Feels more general. Useful for ERC20, ERC721, ERC1155.

**Comment by zerosnacks** [comment]
Thanks for picking this up so quickly, love the implementation as well

**Comment by PaulRBerg** [comment]
This is amazing, thanks! We might end up using it in our [NFT descriptor](https://github.com/sablier-labs/v2-core/blob/fcbc567aea6362c1f102eb19732badeb4899dec5/src/SablierV2NFTDescriptor.sol), which currently uses a custom implementation.

**Comment by PaulRBerg** [comment]
However, a critical safety feature is to be able to truncate up to N characters, or not allow more than N characters. Is this possible with the implementation added in #530?

**Comment by Vectorized** [comment]
@PaulRBerg Possible to add. I’ll add it when I’m back from lunch.

**Comment by Vectorized** [comment]
Ok, I've merged. Lemme know if it's ok.

**Comment by zerosnacks** [comment]
Thanks, @Vectorized LGTM!
