### ISSUE TITLE
✨ Add `_getArgBool(offeset)` to `Clone`

### ISSUE THREAD

**Issue by 0xClandestine** [Vectorized/solady#540]
The code `_getArgUint8(offset) > 0` works, but I think using `_getArgBool(offset)` would make things cleaner. Also, when you use abi.encodePacked(bool), it packs booleans into a single byte (same as uint8). Also, I can't remember off the top of my head, but I'm pretty sure there's a cheaper way to evaluate whether or not a given byte is non-zero.

**Comment by 0xClandestine** [comment]
We could also consider including a `toBool(uint)` function in `SafeCastLib`.

**Comment by Vectorized** [comment]
Wait, just do `x != 0`. And it will convert to bool. Clearer and less characters. The compiler will do it efficiently most of the time.

**Comment by Vectorized** [comment]
Don’t overthink it. 

Also, using `x != 0` will give auditors and reviewers less headaches.

**Comment by 0xClandestine** [comment]
Good point on readability for auditors, also thanks for the tip, will just use `x != 0`. 🫡
