### ISSUE TITLE
should this address be payable?

### ISSUE THREAD

**Issue by WyseNynja** [Vectorized/solady#552]
https://github.com/Vectorized/solady/blob/51444f82fb8907908c5c45783667b27ccc50ce6d/src/utils/LibClone.sol#L564

Given that you emit an event when ETH is received instead of delegating, all the contracts should be considered payable, right?

**Comment by Vectorized** [comment]
Technically, all bytecode clones are payable. 

We choose to simply return a non-payable address as it is the convention used by other libraries. Most codebases store the addresses as non-payable, casting them to payable on-the-fly if needed.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

If you need it to be payable, you can perform the casting manually.

**Comment by Vectorized** [comment]
@WyseNynja Yup. Once it is compiled, there's no gas difference. It's just typing for the compiler.
