### ISSUE TITLE
📖 Use of biblical comment not correct

### ISSUE THREAD

**Issue by sambacha** [Vectorized/solady#558]
https://github.com/Vectorized/solady/blob/efd63173997c6e30a2e45cd889cdd3968598a4c2/src/utils/DateTimeLib.sol#L27

Days as we understand them couldn’t exist until after God completed creation. So the use of days in the biblical context in this comment is not the same as days used in our ordinary vernacular.

Ref: 

Vern S. Poythress, “Rain Water versus a Heavenly Sea in Genesis 1:6-8,” Westminster Theological Journal 77 (2015): 181-91.

Haynes, Matthew, & Krüger, P. Paul. (2017). Creation rest: Genesis 2:1-3 and the first creation account. Old Testament Essays, 30(3), 663-683. https://dx.doi.org/10.17159/2312-3621/2017/v30n3a8

**Comment by ControlCplusControlV** [comment]
When feature flag support to change the comment based on religion?

**Comment by sambacha** [comment]
I should have said incorrect instead of not correct.

Thx @Vectorized for taking this seriously. 😘
