### ISSUE TITLE
✨ Add SafeTransferLib permit support

### ISSUE THREAD

**Issue by 0xClandestine** [Vectorized/solady#560]
Eliminates the need to import `src/tokens/ERC20` when utilizing eip-2612 permits. 

This aligns with the current functionality of `SafeTransferLib`, which already negates the need to import `ERC20` for approvals, balance checks, and transfers.

```solidity
token.safeTransferFrom(from, to, signature)
// token.safeTransferFrom(from, to, abi.encodePacked(r, s, v))

token.safePermit(owner, spender, value, deadline, signature)
// token.safePermit(owner, spender, value, deadline, abi.encodePacked(r, s, v))
```

**Comment by Atarpara** [comment]
@0xClandestine as per [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612#specification) standard permit has signature format  is `v`,`r` and `s`. so i think we keep as it is for better optimization.

**Comment by Vectorized** [comment]
@0xClandestine Can you clarify how is `token.safeTransferFrom(from, to, signature)`  implemented internally?

Imo, I'd just add a function to handle permit. There's not much efficiency gains from combining it with transfer.

**Comment by Vectorized** [comment]
I feel that this function doesn't really need to be coded.

The reason being that `permit` has many variables, and that different codebases may use different tricks to circumvent stack too deep.

**Comment by 0xClandestine** [comment]
> @0xClandestine Can you clarify how is `token.safeTransferFrom(from, to, signature)` implemented internally?
> 
> Imo, I'd just add a function to handle permit. There's not much efficiency gains from combining it with transfer.

Good point, to be honest `safeTransferFrom()` really isn't needed, could see some benefit of adding `safePermit()` though. Also, wondering if stack-too-deep is thrown when compiling a library function that's not being used since. Iirc the compiler ignores unused internal methods. 🤔

**Comment by 0xClandestine** [comment]
> @0xClandestine as per [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612#specification) standard permit has signature format is `v`,`r` and `s`. so i think we keep as it is for better optimization.

That's my bad, I originally included both aliases in the example, but figured the above ones conveyed the same idea.

**Comment by Vectorized** [comment]
Do you have an example of a codebase that uses `ERC20.permit` internally?

Want to get a feel of it.
