### ISSUE TITLE
📏 EIP-6093

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#597]
A standard for token custom errors will finalize soon. Might as well incorporate, no? https://eips.ethereum.org/EIPS/eip-6093

**Comment by Vectorized** [comment]
Feels bloated and OpenZeppelin centric. 

Stuff like:
```
// Revert if the caller is not the owner, nor approved.
if iszero(or(eq(caller(), from), eq(caller(), approvedAddress))) {
    if iszero(sload(keccak256(0x0c, 0x30))) {
        mstore(0x00, 0x4b6e7f18) // `NotOwnerNorApproved()`.
        revert(0x1c, 0x04)
    }
}
```
will have to be de-optimized to account for the different types of errors.

I don't like it.

**Comment by benaadams** [comment]
Was just above to open this

Asked and answered 😅

**Comment by z0r0z** [comment]
gg @Vectorized I feel yaz 😆 I will leave this open to get more feels. Overall, I don't jive with this as a contract guy, but it probably goes to help out appside devs. Le standardization format.
