### ISSUE TITLE
✨ EIP712 view name and version

### ISSUE THREAD

**Issue by noyyyy** [Vectorized/solady#611]
Just tried the EIP712 contract and found that I need to override `_domainNameAndVersion` to give name and version.

What if I want to configure name and version in contructor rather make them constant, like openzepplin's EIP721 implementation. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/EIP712.sol

I know this case is less gas effective, will this case be considered?

**Comment by Vectorized** [comment]
Nope. 

It will make the library not compatible with proxies (clones, upgradeable contracts).

Solady will only have a single repo. There will not be a Solady-upgradeable created via a transpiler (which is what ERC721A and OpenZeppelin is using). Reason being the transpiler can’t handle custom storage layouts.

**Comment by noyyyy** [comment]
The case I am referring to is not a upgradable contract case. 
Currently, I have to hard encode the name and version in contract, like: 


```solidity
function _domainNameAndVersion() internal pure override returns (string memory n, string memory v) {
        n = "name";
        v = "version";
    }
```


If I write something like

```solidity
string private _name;
string private _version;

 constructor(string memory name_, string memory version_) {
        _name = name_;
        _version = version_;
    }

function _domainNameAndVersion() internal pure override returns (string memory n, string memory v) {
        n =  _name;
        v = _version;
    }
```

It will lead to compile error, since `_domainNameAndVersion` read the storage, it should be marked as view but you cannot override a function from pure to view.


Can I not hard encode name and version?

**Comment by Vectorized** [comment]
What’s your use case for passing in the name and version in the constructor?

**Comment by noyyyy** [comment]
> What’s your use case for passing in the name and version in the constructor?

Just for being comfortable to not hard code args. Just for the format of code.

I think I get your idea. It's ok to hard code some args for gas efficiency.

**Comment by Vectorized** [comment]
We may make the function view and add a `_domainNameAndVersionIsPure()` function that must be overridden to return false if the function reads from storage. 

Let’s see if the compiler can handle that efficiently.

**Comment by noyyyy** [comment]
> We may make the function view and add a `_domainNameAndVersionIsPure()` function that must be overridden to return false if the function reads from storage.
> 
> Let’s see if the compiler can handle that efficiently. Hopefully it does.

That could be nice! Let the data speak.
