### ISSUE TITLE
📝 Adjust SafeTransferLib docs to more accurately reflect vulnerability related to usage of force invariants

### ISSUE THREAD

**Issue by kadenzipfel** [Vectorized/solady#613]
SafeTransferLib.sol includes comments stating: "If gas griefing protection is needed, please use the force variants."

Because the regular variants validate that the subcall was successful, they're not vulnerable to [gas griefing attacks](https://kadenzipfel.github.io/smart-contract-vulnerabilities/vulnerabilities/insufficient-gas-griefing.html). Rather the attack that they're vulnerable to is [DoS with unexpected revert](https://kadenzipfel.github.io/smart-contract-vulnerabilities/vulnerabilities/dos-revert.html)

The documentation should reflect this

**Comment by Vectorized** [comment]
The non-force variants are vulnerable to both DoS and gas griefing. 

"If gas griefing protection is needed, please use the force variants." -> 
"IIf the ETH transfer MUST succeed with a reasonable gas budget, use the force variants."

**Comment by kadenzipfel** [comment]
> "If gas griefing protection is needed, please use the force variants." -> "IIf the ETH transfer MUST succeed with a reasonable gas budget, use the force variants."

This is a good adjustment
