### ISSUE TITLE
🪙 ERC223

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#628]
After more than 6 years in EIP hell it looks like the madlad @Dexaran finally got [ERC-223: Token with transaction handling model](https://eips.ethereum.org/EIPS/eip-223) published as a token standard interface. Wdwt as to inclusion as optimized reference~~

Pros:
- Simple.
- Lowass number (223).
- Optimal for defi with send receipts.

Cons:
- Hafta implement bespoke receivers.
- Prob some security minded stuff but,
it has been review for 6 years, seems ok.

**Comment by Dexaran** [comment]
FYI here you can find more info regarding ERC-223 as well as some old discussions https://dexaran.github.io/erc223/

Regarding security considerations - 


- ERC-20 is not secure. It resulted in [$130M worth of tokens being lost](https://www.reddit.com/r/ethereum/comments/15hdz96/today_at_least_130m_worth_of_tokens_are_lost/?utm_source=share&utm_medium=web2x&context=3). So, ERC-223 is exactly a "security patch" for ERC-20 standard.

- Reentrancy issues must be taken into account when dealing with ERC-223 tokens. ERC-223 makes "tokens" behave identical to "ether".

- `tokenReceived` function must be invoked AFTER the balance change in the token contract.

**Comment by z0r0z** [comment]
closin for now. I expect that we might see more of these kinds of use cases handled by SCA batch calls.
