### ISSUE TITLE
🗞️ Calldata Compressed Proxy

### ISSUE THREAD

**Issue by z0r0z** [Vectorized/solady#630]
For rollups nsuch a calldata compression proxy contract pattern seems amenable, no? via [LibZip ](https://github.com/Vectorized/solady/blob/main/src/utils/LibZip.sol)

**Comment by z0r0z** [comment]
Fair ~~ would a `Proxy` standalone be useful or is that more or less covered in LibClone yt https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Proxy.sol

**Comment by Vectorized** [comment]
`LibZip.cdFallback` has gotta be on the implementation itself, not the proxy. 

It is to be triggered only when the first 4 bytes of the calldata doesn't match any of the function selectors on the implementation.
