### ISSUE TITLE
Add `toHexStringChecksumed` as an alias for `toHexStringChecksummed`

### ISSUE THREAD

**Issue by RogerPodacter** [Vectorized/solady#771]
In my opinion, breaking an API should be reserved for fixing a bug or adding a feature, not fixing a harmless typo.

Plus, who knows—this could be Solady's chance at an iconic HTTP `referer` level of pop culture penetration!!

**Comment by Vectorized** [comment]
Oh my! The lore potential is definitely juicy.

**Comment by RogerPodacter** [comment]
Also can `append` be an alias for `p`? I'm getting roasted for now-out of date advice I've given people lol.

You can't do the humble journeyman hipster "everything is a point release" meme and then ALSO make these breaking changes... again strictly in my very humble opinion.

(It kills me to write this because you know I like the `p` thing)

**Comment by Vectorized** [comment]
Ah, there are too many small breaking changes in the history. And I really like how concise the file is with `p`.

**Comment by RogerPodacter** [comment]
`p` is really nice! Ok I'll continue educating!! Honestly it's nice to be hit up about Solidity for a change!
