### ISSUE TITLE
✨ RingBufferLib

### ISSUE THREAD

**Issue by kaliubuntu0206** [Vectorized/solady#774]
It would be great if we have an AMM contract with gas optimized version. Uniswap V2 would be a great start.

**Comment by kaliubuntu0206** [comment]
The original idea is here https://github.com/transmissions11/solmate/issues/312 . Maybe @transmissions11 forgot to implement or doesn't have time.

**Comment by Vectorized** [comment]
It's not AMM. 

It's a ring buffer (a datastructure).

https://github.com/euler-xyz/median-oracle/blob/master/README.md#ring-buffer

**Comment by Vectorized** [comment]
Not sure how specific it should be. 32 bits? 128 bits? A decision required for storage packing.

Not sure if it should be in a library. 

Protocol devs usually have way more domain specific knowledge, and that is crucial for optimization.

Leaving this open. Let's chill and see if we can get more clarity.

More specificity = More gas savings = Less flexibility.
