### ISSUE TITLE
❌ Bug in SearchSorted in LibSort

### ISSUE THREAD

**Issue by Atarpara** [Vectorized/solady#79]
I found one bug in searchSorted function. 

when `needle == array.length` and needle is not in array then it return always `true`. It happen due underflowing `high := sub(high,0x20)`. 

>  **_NOTE:_** All Element must be greater than needle to reproduce is issue.

Example :
```
a = [2]
needle  = 1
LibSort.searchSorted(a,1) -> (true,0)

a = [45,46]
needle  = 2
LibSort.searchSorted(a,1) -> (true,0)


```

**Comment by Vectorized** [comment]
Wow! Great find!
