### ISSUE TITLE
⚡️ERC721: Combine _mint() and set _setExtraData() into single SSTORE

### ISSUE THREAD

**Issue by 0xbid** [Vectorized/solady#796]
Currently, the ownership slot can be extended with `extraData` to make use of the extra bits. I've used this feature extensively and it leads to gas savings due to re-using the same slot, which is great.

However, the functions are different and and SSTORE operation happens separately, causing more gas the be used than necessary.

Everytime I've used _setExtraData, it's been right after a _mint, and this seems like a very common pattern from what I've seen others do.

It would be great if there was a single function, `_mintAndSetExtraData`, that does a single SSTORE instead.

**Comment by Vectorized** [comment]
Hmm... I didn't add it because it will make the code feel bloaty. 

But i get the feeling of wanting to save that last 1k gas.

If this is to be implemented, it will only be for the `_mint` function. 

If someone somehow needs `_safeMint`, I'm pretty sure they don't care about gas; so we can ignore the `_safeMint` variants.

**Comment by 0xbid** [comment]
Agree completely, most of the usefulness would come from extending just `_mint`.

**Comment by atarpara** [comment]
@Vectorized Solady ERC721 is designed such that minting, transferring, and burning don't affect the extra data. However, introducing this feature in Solady will result in a breaking change. One potential solution is to implement a new function called `mintWithSetData`. This function would essentially be a copy of the `_mint` function, but adding it would introduce duplicate code and increase the bytecode size.

**Comment by Vectorized** [comment]
@atarpara Yes, it will require a separate function.

Internal functions are not added to the bytecode unless they are used. 

Due to aesthetics, and to avoid touching an audited file, I may not actually include this unless. 

Right now, gas prices are still reasonable. May reserve this for a future date when ETH hits $3000.

**Comment by 0xbid** [comment]
Is it really only 1k gas extra for calling `_mint` and then `_setExtraData`? My understanding of SSTORE is that the first use on the slot would be 20k, then the second one would be 5k, and if this were the case the savings would also be closer to 4k.

And this doesn't even take into the additional compute of having to re-calculate some steps to refer to the right slot, so maybe an additional 100 for that.

**Comment by 0xbid** [comment]
> Right now, gas prices are still reasonable. May reserve this for a future date when ETH hits $3000+.

@Vectorized I'm down to just run make the modifications in my own copy of the lib, and be the first to experiment with the intended code. Would also validate via my own tests as well - that way you can have a high degree of confidence even before it gets to that point.

 I think all that is needed is to combine these two functions:
```Solidity
    function _setExtraData(uint256 id, uint96 value) internal virtual {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x00, id)
            mstore(0x1c, _ERC721_MASTER_SLOT_SEED)
            let ownershipSlot := add(id, add(id, keccak256(0x00, 0x20)))
            let packed := sload(ownershipSlot)
            sstore(ownershipSlot, xor(packed, shl(160, xor(value, shr(160, packed)))))
        }
    }

    function _mint(address to, uint256 id) internal virtual {
        _beforeTokenTransfer(address(0), to, id);
        /// @solidity memory-safe-assembly
        assembly {
            // Clear the upper 96 bits.
            to := shr(96, shl(96, to))
            // Revert if `to` is the zero address.
            if iszero(to) {
                mstore(0x00, 0xea553b34) // `TransferToZeroAddress()`.
                revert(0x1c, 0x04)
            }
            // Load the ownership data.
            mstore(0x00, id)
            mstore(0x1c, _ERC721_MASTER_SLOT_SEED)
            let ownershipSlot := add(id, add(id, keccak256(0x00, 0x20)))
            let ownershipPacked := sload(ownershipSlot)
            // Revert if the token already exists.
            if shl(96, ownershipPacked) {
                mstore(0x00, 0xc991cbb1) // `TokenAlreadyExists()`.
                revert(0x1c, 0x04)
            }
            // Update with the owner.
            sstore(ownershipSlot, or(ownershipPacked, to))
            // Increment the balance of the owner.
            {
                mstore(0x00, to)
                let balanceSlot := keccak256(0x0c, 0x1c)
                let balanceSlotPacked := add(sload(balanceSlot), 1)
                if iszero(and(balanceSlotPacked, _MAX_ACCOUNT_BALANCE)) {
                    mstore(0x00, 0x01336cea) // `AccountBalanceOverflow()`.
                    revert(0x1c, 0x04)
                }
                sstore(balanceSlot, balanceSlotPacked)
            }
            // Emit the {Transfer} event.
            log4(codesize(), 0x00, _TRANSFER_EVENT_SIGNATURE, 0, to, id)
        }
        _afterTokenTransfer(address(0), to, id);
    }
```

I'd give it a go but not as confident in my Yul skills 😄 - want to give it a shot?

**Comment by atarpara** [comment]
@Vectorized In my dream i show ETH price is $4000.

**Comment by Vectorized** [comment]
After more marinating, I think let's push this function further.

`_mintAndSetExtraDataUnchecked`.

- Doesn't check for zero address. I assume you will use `msg.sender`, otherwise just add your own check ;).
- Doesn't check if the token already exists.

This is the final form, and I can feel the immense gas savings.
