### ISSUE TITLE
`match` used in assembly is a reserved keyword.

### ISSUE THREAD

**Issue by anudit** [Vectorized/solady#817]
Ref: https://github.com/Vectorized/solady/blob/54ea1543a229b88b44ccb6ec5ea570135811a7d9/src/utils/LibZip.sol#L49

While using LibZip in a Hardhat project and testing coverage using `npx hardhat coverage` the compilation errors out.

![image](https://github.com/Vectorized/solady/assets/12015553/116da03e-d1c1-4a67-b282-3fe6efc14823)

Turns out `match` is a reserved keyword https://docs.soliditylang.org/en/latest/units-and-global-variables.html#reserved-keywords. 

Changing `match` to anything else makes it work.

solidity-coverage: `v0.8.6`
solidity: `0.8.23`

**Comment by Vectorized** [comment]
@anudit Pushed a new version of Solady 0.0.167.

**Comment by anudit** [comment]
Thanks @Vectorized @atarpara ! At 23% savings on compressed calldata.

**Comment by atarpara** [comment]
@anudit you can also try `cdCompress()` function might be you get more gas saving on decompression.

**Comment by Vectorized** [comment]
I heard `cdCompress` + `flzCompress` can synergize on some kinds of data.

**Comment by anudit** [comment]
@Vectorized @atarpara  Some quick numbers on compressing Groth16 Proofs with some extra calldata for [omnid.io](https://omnid.io). 

| Method                                                   | Calldata Savings (Single - Multiple proofs) | Gas Overhead      |
|----------------------------------------------------------|---------------------------------------------|-------------------|
| `cdCompress` & `cdDecompress`                            | 7-23%                                       | 39k - 77k         |
| `flzCompress` & `flzDecompress`                          | 0-22%                                       | 10.5k - 21k       |
| `flzCompress(cdCompress())` & `cdDecompress(flzDecompress())` | 0-25%                                   | 41k - 81k         |
| `cdCompress(flzCompress())` & `flzDecompress(cdDecompress())` | 0-22%                                   | 50k - 97k         |


`flzCompress` & `flzDecompress` seems to work the best for this usecase.
