### ISSUE TITLE
⚠️ Potential Error in _hashTypedData Assembly Code Leading to Incorrect EIP-712 Digest Calculation

### ISSUE THREAD

**Issue by codemedici** [Vectorized/solady#825]
Hello,

I've been reviewing the `_hashTypedData` function within `EIP712.sol`, in particular the following line Located at [EIP712.sol#L138](https://github.com/Vectorized/solady/blob/1372606383445c0a247e6c58eb255a529734258a/src/utils/EIP712.sol#L138):

`digest := keccak256(0x18, 0x42)`

To my understanding, the data prepared for hashing actually starts at 0x00 (where the prefix "\x19\x01" is stored), not at 0x18, while 0x42 correctly represents the total size of the data segment to be hashed.

Tbh I can't figure out the reasoning behind the other offsets either, if you could please clarify so that I could use your code in production.

Thank you!

**Comment by Vectorized** [comment]
When you store `0x1901000000000000` at slot `0x00`, here is how the memory looks like:

```
<----------------- 0x18 bytes ----------------->
0000000000000000000000000000000000000000000000001901000000000000
```
