### ISSUE TITLE
👷‍♂️ Slither unable to generate IR for LibSort

### ISSUE THREAD

**Issue by sambacha** [Vectorized/solady#847]
Using the latest `slither` release and latest `LibSort`, Slither is unable to generate an IR for LibSort. It gives the following error message:

~~~~console
$ slither
ERROR:ContractSolcParsing:Impossible to generate IR for LibSort._toInts (lib/solady/src/utils/LibSort.sol#535-540):
 'str' object has no attribute 'type'
~~~

**Comment by Vectorized** [comment]
@0xalpharush

**Comment by Vectorized** [comment]
Could be related: https://github.com/crytic/slither/issues/1966

**Comment by 0xalpharush** [comment]
This is the same regression as https://github.com/crytic/slither/issues/2210. Will get it fixed!

**Comment by 0xalpharush** [comment]
This should be fixed in the latest release https://github.com/crytic/slither/releases/tag/0.10.2

**Comment by Vectorized** [comment]
Much kudos!
