### ISSUE TITLE
⚡ Avoiding balance cold storage reset for tokens

### ISSUE THREAD

**Issue by codeislight1** [Vectorized/solady#849]
Hola amigos,

Since there is always a case when transferring tokens, a user might receive again a certain amount of tokens which would lead to incur a cold storage set. so maybe we can treat balance of 1 as 0, thus avoiding the reset altogether. thoughts?

- totalSupply must be less than or equal to type(uint256).max - 1
- mint 
   - userBalance += if userBalance == 0 ? amount + 1 : amount
   - totalSupply += amount
- burn amount
   - userBalance -= amount
   - totalSupply -= amount
- transfer:
   - receiverBalance += if receiverBalance == 0 ? amount + 1 : amount
   - senderBalance -= amount
- balanceOf
   - return: if balance == 0 ? 0 : balance - 1

**Comment by Vectorized** [comment]
It's ok. Let's keep the code simple. The extra if-else is extra overhead. And would require re-audit.

**Comment by codeislight1** [comment]
roger!
