### ISSUE TITLE
Feature:  URL Encoding safe Base64

### ISSUE THREAD

**Issue by sambacha** [Vectorized/solady#850]
# Consider adding URL Safe Encoding for Base64 Library

Base64 URL Safe Encoding is defined in RFC468 section § 5[^1], whereas the current Base64 specification is defined in [RFC 4648 § 4](https://datatracker.ietf.org/doc/html/rfc4648#section-4)

To avoid the errors, it was proposed to use a “safe alphabet” for URL addresses and filenames. 

- Replaces “+” by “-” (minus)
- Replaces “/” by “_” (underline)
- Does not require a padding character
- Forbids line separators

The alphabet:

ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_[^2]

## References

[^1]: https://datatracker.ietf.org/doc/html/rfc4648#section-5
[^2]: It should fit the format `^[A-Za-z0-9+/]+={0,2}$`

**Comment by Vectorized** [comment]
@sambacha Already implemented. 

Pass in `true` for the `fileSafe` parameter: https://github.com/Vectorized/solady/blob/d3d564a3451f7128d63e611ac972b37804bd2c21/src/utils/Base64.sol#L11

**Comment by sambacha** [comment]
> @sambacha Already implemented.
> 
> Pass in `true` for the `fileSafe` parameter:
> 
> https://github.com/Vectorized/solady/blob/d3d564a3451f7128d63e611ac972b37804bd2c21/src/utils/Base64.sol#L11

The problem is with using `=` as the padding character - it is used to send data via query string as “key=value” pair.

**Comment by Vectorized** [comment]
What about setting `noPadding` to `true` too?
