### ISSUE TITLE
Error in verifying git while installing 

### ISSUE THREAD

**Issue by parzivalishan** [Vectorized/solady#872]
ci@ishan:~$ forge install vectorized/solady
Installing solady in /home/ci/lib/solady (url: Some("https://github.com/vectorized/solady"), tag: None)
Error:
git status exited with code 128:
fatal: not a git repository (or any of the parent directories): .git

**Comment by Vectorized** [comment]
@atarpara 

Can help me check? Last I tried it works on my machine.

**Comment by atarpara** [comment]
@parzivalishan It happened due to git is not initialize in his local directory (`.git` folder is missing).

please try first execute

`git init` or `forge init`
